#!/usr/bin/env python

import os
import sys
import time
import datetime
import pygtk
pygtk.require('2.0')
import gtk
import gtk.glade
import gobject
import pynotify
import pyglet

class ContextMenu():
	def __init__(self, button, activate_time):
		self.button = button
		self.activate_time = activate_time

		menu = gtk.Menu()
		menu_item = gtk.ImageMenuItem('gtk-quit')
		menu_item.connect('activate', self.on_quit_clicked)
		menu_item.show()
		menu.append(menu_item)
		menu.show()
		menu.popup(None, None, None, button, activate_time)

	def on_quit_clicked(self, menu_item):
		gtk.main_quit()

class TimerSetter():
	def __init__(self):
		self.bin_path = os.path.dirname(os.path.realpath(sys.argv[0]))
		self.gladefile = os.path.join(self.bin_path, 'gcountdown.glade')
		self.alert_time = None
		self.alert_msg = None
		self.play_sound = False

		self.wtree = gtk.glade.XML(self.gladefile)
		self.window = self.wtree.get_widget("window_main")
		self.window.connect("destroy", self.on_window_main_destroy)
		sighandlers = {
			'on_button_apply_clicked': self.on_button_apply_clicked,
			'on_button_cancel_clicked': self.on_button_cancel_clicked,
		}
		self.wtree.signal_autoconnect(sighandlers)

	def main(self, alert_msg):
		self.wtree.get_widget("entry_message").set_text(alert_msg)
		self.window.show()
		gtk.main()
		self.window.hide()
		return((self.alert_time, self.alert_msg, self.play_sound))

	def on_window_main_destroy(self, *args):
		gtk.main_quit()

	def on_button_apply_clicked(self, *args):
		now = datetime.datetime.now()
		self.alert_time = now + datetime.timedelta(
			hours = self.wtree.get_widget("spinbutton_hours").get_value_as_int(),
			minutes = self.wtree.get_widget("spinbutton_mins").get_value_as_int(),
			seconds = self.wtree.get_widget("spinbutton_secs").get_value_as_int()
		)
		self.alert_msg = self.wtree.get_widget("entry_message").get_text()
		self.play_sound = self.wtree.get_widget("checkbutton_sound").get_active()
		gtk.main_quit()

	def on_button_cancel_clicked(self, *args):
		gtk.main_quit()

class Timer:
	def __init__(self):
		self.icon_path = os.path.dirname(os.path.realpath(sys.argv[0]))
		self.icon_idle = os.path.join(self.icon_path, 'idle.png')
		self.icon_running = os.path.join(self.icon_path, 'running.png')
		self.icon_alarm = os.path.join(self.icon_path, 'alarm.png')
		self.tick_interval = 1
		self.alert_time = None # When to alert
		self.alert_msg = "Pizza's done!" # What to alert
		self.play_sound = False
		self.alerted = False # Have we already alerted for the current alert?
		self.editing = False # Are we editing an alert (don't open new edit window)

		self.icon = gtk.status_icon_new_from_file(self.icon_idle)
		self.icon.connect('activate',self.on_icon_clicked)
		self.icon.connect('popup-menu',self.on_icon_popup_menu)
		self.icon.set_visible(True)

		self.alert_reset()

	def on_icon_popup_menu(self, icon, button, activate_time):
		ContextMenu(button, activate_time)

	def alert_set(self, alert_time, alert_msg, play_sound):
		self.icon.set_from_file(self.icon_running)
		self.alert_time = alert_time
		self.alert_msg = alert_msg
		self.play_sound = play_sound

	def alert_reset(self):
		self.icon.set_from_file(self.icon_idle)
		self.alert_time = None
		self.alerted = False
		self.icon.set_tooltip("Idle")
		self.icon.set_blinking(False)

	def on_icon_clicked(self,dummy):
		if self.alerted:
			self.alert_reset()
		else:
			if not self.editing:
				self.editing = True
				w = TimerSetter()
				alert_time, alert_msg, play_sound = w.main(self.alert_msg)
				if alert_time and alert_msg:
					self.alert_set(alert_time, alert_msg, play_sound)
				else:
					self.alert_reset()
				self.editing = False

	def delta_frac(self, delta):
		delta_mins, delta_secs = divmod(delta.seconds, 60)
		delta_hours, delta_mins = divmod(delta_mins, 60)
		return( {'hours': delta_hours, 'mins': delta_mins, 'secs': delta_secs} )

	def update(self):
		now = datetime.datetime.now()
		if self.alert_time:
			if now >= self.alert_time:
				# Show elapsed time since alert in tooltip
				d = self.delta_frac(now - self.alert_time)
				self.icon.set_tooltip(
					"%s - %i hours, %i minutes and %i seconds ago" % (
						self.alert_msg, d['hours'], d['mins'], d['secs'])
				)

				# Sound the alarm if we haven't done so yet
				if not self.alerted:
					# Change icon
					self.icon.set_from_file(self.icon_alarm)
					self.icon.set_tooltip(self.alert_msg)
					self.icon.set_blinking(True)

					# Play sound
					if self.play_sound:
						sound = pyglet.media.load('apert.wav', streaming=False)
						smanager = sound.play()

					# Show notification
					pynotify.init('Timer')
					notifier = pynotify.Notification(self.alert_msg, 'The timer you set has run out. Click the bell icon to reset it.', 'file://%s' % (self.icon_alarm))
					notifier.set_urgency(pynotify.URGENCY_CRITICAL)
					notifier.set_hint('x', self.icon.get_geometry()[1].x)
					notifier.set_hint('y', self.icon.get_geometry()[1].x)
					notifier.set_timeout(5)
					notifier.show()
					self.alerted = True
			else:
				# Show time left to alert in tooltip
				d = self.delta_frac(self.alert_time - now)
				self.icon.set_tooltip("Alerting in %i hours, %i minutes, %i seconds" % (
					d['hours'], d['mins'], d['secs'])
				)

		source_id = gobject.timeout_add(self.tick_interval*1000, self.update)

	def main(self):
		gobject.timeout_add(self.tick_interval, self.update)
		gtk.main()

if __name__ == "__main__":
	working_dir = os.path.dirname(os.path.realpath(sys.argv[0]))
	os.chdir(working_dir)

	app = Timer()
	app.main()
